# Generated by Django 3.0.8 on 2020-08-29 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('info', models.CharField(max_length=100)),
                ('imgUrl', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('Tecnology', 'TECNOLOGY'), ('Automotive', 'AUTOMOTIVE'), ('Toys', 'TOYS'), ('Fashion', 'FASHION'), ('Books', 'BOOKS'), ('Pet Shop', 'PET SHOP'), ('Watches', 'WATCHES'), ('Antique', 'ANTIQUE'), ('Music Instruments', 'MUSIC INTRUMENTS')], max_length=17)),
                ('higuestbid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('isActive', models.BooleanField()),
                ('bids', models.ManyToManyField(blank=True, related_name='bids', to='auctions.Bid')),
                ('comments', models.ManyToManyField(blank=True, related_name='comments', to='auctions.Comment')),
                ('isWatchOfThoseUsers', models.ManyToManyField(blank=True, related_name='usersWatch', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
