# Generated by Django 3.0.8 on 2020-08-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200813_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(choices=[('Tecnology', 'TECNOLOGY'), ('Automotive', 'AUTOMOTIVE'), ('Toys', 'TOYS'), ('Fashion', 'FASHION'), ('Books', 'BOOKS'), ('Pet Shop', 'PET SHOP'), ('Watches', 'WATCHES'), ('Antique', 'ANTIQUE'), ('Music Instruments', 'MUSIC INTRUMENTS')], max_length=17),
        ),
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
