# Generated by Django 3.0.8 on 2020-08-15 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200813_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='onwer',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='onwer',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='isWatch',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
