# Generated by Django 3.0.8 on 2020-08-18 00:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200816_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='isWatchOfThoseUsers',
            field=models.ManyToManyField(blank=True, related_name='usersWatch', to=settings.AUTH_USER_MODEL),
        ),
    ]
